### ISSUE TITLE
gettersSetters option support

### ISSUE THREAD

**Issue by alexbeletsky** [fergaldoyle/modelOptions#2]
Great module, using that actively. Is gettersSetters support will be provided?

**Comment by fergaldoyle** [comment]
No plans update this module.

You might be interested in this build of Angular 1.3 / 1.4 with added IE8 support. Meaning you'll get all ngModelOptions functionality:
https://github.com/fergaldoyle/angular.js-ie8-builds

**Comment by alexbeletsky** [comment]
@fergaldoyle thanks a lot for the info! You are right, in my case I should consider upgrade to 1.4.
